### ISSUE TITLE
aggregate name: identity

### ISSUE THREAD

**Issue by jangorecki** [smartinsightsfromdata/rpivotTable#105]
There could be one more function to just print the value as is. It is of course valid only when all value cells are length 1. Now use has to use `Average` which might be misleading when it is known that single value is in each cell.

**Comment by nicolaskruchten** [comment]
This is what List does :)

**Comment by jangorecki** [comment]
make sense, but the problem is that when selecting `list unique values` the height of cells is multiplied by ~5 which makes table not very read-able.

**Comment by nicolaskruchten** [comment]
Yes, you end up listing the unique values in the total rows and cols, which sometimes distorts things. It's not clear what "identity" would do differently for the total cells.

**Comment by jangorecki** [comment]
@nicolaskruchten I don't think we could define "identity" for an aggregated measure, thus should be NA/empty

**Comment by nicolaskruchten** [comment]
Sure, there are many ways to do this. If you want to add an aggregator here in the R binding you can do so by following the aggregator docs in the JS repo, but At this time I don’t want to add any more overlapping default aggregators at the JS layer. We have first/last/list already...

**Comment by jangorecki** [comment]
OK, so the "average" has to stay in my case.

**Comment by nicolaskruchten** [comment]
I tend to use min or max or first or last myself. First/last work with strings, whereas average doesn’t.
