### ISSUE TITLE
reduce area of metadata in output table

### ISSUE THREAD

**Issue by jangorecki** [smartinsightsfromdata/rpivotTable#107]
By metadata I mean the area used to select columns, as opposed to data area where values are printed.
So the issue is about make the table looks more tidy. In an example below.
![Screenshot_2019-11-05_15-55-48](https://user-images.githubusercontent.com/3627377/68200389-c3dac980-ffe5-11e9-85e1-bc966b1feb2e.png)
You can see that "A" in unnecessarily wide, similarly as "B".
I would like to:
1. make "A" as wide as it is necessary - according to width of field names listed in this column
2. move whole rectangle marked as "B" to the top of whole table, to have it above of the table, it is not very useful to have it on the left side as it waste a lot of space. I see it is made like this in react-pivottable.js: https://react-pivottable.js.org/ example.
3. if point 2 is not possible, then I would like to make "C" according to point 1, but still I have we should aim to have 2. resolved

**Comment by smartinsightsfromdata** [comment]
@nicolaskruchten see also #108 

Do you see a way to solve this via pivotable css?

**Comment by nicolaskruchten** [comment]
You can do just about anything in CSS, yes, and you can use the `unusedAttrsVertical` parameter in pivottable.js to force the unused attribute area (the "metadata" as you call it) to always be above.

**Comment by jangorecki** [comment]
thanks @nicolaskruchten, works fine!
still the width of "A" could be improve as it doesn't have to be such wide
