### ISSUE TITLE
citing rpivottable

### ISSUE THREAD

**Issue by vnijs** [smartinsightsfromdata/rpivotTable#13]
I would like to provide some citation to the packages used in my app. Generating the citation for rpivottable only works partially (see message below). 

Warning in citation(i): no date field in DESCRIPTION file of package
'rpivotTable'

See links below where I mention your package in the helpfiles.

http://mostly-harmless.github.io/radiant/about.html
http://mostly-harmless.github.io/radiant/base/pivot.html

**Comment by smartinsightsfromdata** [comment]
@mostly-harmless thanks for this.  I'll fix the description.  Thanks for reporting it.

**Comment by smartinsightsfromdata** [comment]
@mostly-harmless  Date field added to description.  Please note as well the new c3 renderers for line and bar charting.

**Comment by mostly-harmless** [comment]
Thanks! The C3 renderers are a very nice addition
