### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by vnijs** [smartinsightsfromdata/rpivotTable#14]
Are you planning to push rpivotTable to CRAN? I think everything works with the version of htmlwidgets on CRAN

**Comment by smartinsightsfromdata** [comment]
@mostly-harmless Definitely, as soon as I have time (in the next few days)!

**Comment by mostly-harmless** [comment]
Excellent. Thanks. I decided to submit my app to CRAN. FWIW Hadley's book on R-packages was very usefull: http://r-pkgs.had.co.nz/release.html

**Comment by vnijs** [comment]
Any updates on the CRAN time-line? Thanks Enzo

**Comment by vnijs** [comment]
Any updates on the CRAN time-line? Thanks Enzo

**Comment by smartinsightsfromdata** [comment]
@vnijs on CRAN from today.   Thanks for your patience.
