### ISSUE TITLE
Charts are missing from renderer dropdown.

### ISSUE THREAD

**Issue by williamjwest** [smartinsightsfromdata/rpivotTable#15]
First off, this is a great package.  When I run this in Rstudio, I do not have the option of selecting "Bar Chart", "Area Chart", or "Line Chart".  Is this expected?

**Comment by smartinsightsfromdata** [comment]
@williamjwest thanks (any merit goes to @nicolaskruchten really, the developer of the original library). 
The functionalities you are referring to are coming from a renderer that uses Google APIs.  As per the terms of the Google API license they can be accessed only online (i.e. they cannot be stored in a folder as part of your project like jquery etc.). 
htmlwidgets, the library developed by @ramnathv and rstudio (e.g. @jcheng5 etc.), does not allow binding online libraries (it would break the general model that calls for compatibility and "same-use" across R, shiny, knitr etc.).

I have requested to have the chance to do this "as an exception" (i.e. extending htmlwidgets to include this as an option) but so far it hasn't happened. 

Theoretically one could develop R bindings independently from htmlwidgets, but I think what you would loose is more than what you would gain.

**Comment by smartinsightsfromdata** [comment]
@williamjwest Actually, I've just noticed that Nicolas has added c3 renderers for bar charts and line graphs: I'll work on adding these asap!

**Comment by smartinsightsfromdata** [comment]
@williamjwest Done!.  Version 0.1.3.1 has the c3 renderer for line charting and bar charting.

Please note that it is possible to have these renderers as the respective library comply with htmlwidgets expectations (i.e. it can be downloaded).  This makes this functionality available across the board.

**Comment by nicolaskruchten** [comment]
@smartinsightsfromdata nice job :) this is exactly the kind of thing which I was hoping to enable with the C3 charting

**Comment by williamjwest** [comment]
@smartinsightsfromdata <https://github.com/smartinsightsfromdata> Awesome
and amazing. I'll try it out this evening.

On Mon, Mar 16, 2015 at 3:39 PM, Enzo <notifications@github.com> wrote:

> @williamjwest <https://github.com/williamjwest> Done!. Version 0.1.3.1
> has the c3 renderer for line charting and bar charting.
>
> Please note that it is possible to have these renderers as the respective
> library comply with htmlwidgets expectations (i.e. it can be downloaded).
> This makes this functionality available across the board.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartinsightsfromdata/rpivotTable/issues/15#issuecomment-81891908>
> .
>



-- 
williamjwest@gmail.com
864-906-3603

**Comment by smartinsightsfromdata** [comment]
@williamjwest  I assume I can close this issue now.
