### ISSUE TITLE
sorting value labels for factors in Tables

### ISSUE THREAD

**Issue by steventroysimpson** [smartinsightsfromdata/rpivotTable#17]
Hi I'm really impressed with your implementation of pivot tables. I just have a bit of cosmetic issue: I'm trying to get output for a low/medium/high factor variable to have tabular out put that prints in the right order instead of alphabetical: high/ low/ medium

I saw in [nicolas.kruchten's example](http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html) where he tries to sort the labels in the javascript he does some special sortAs variable and then specificies the attributes for the day and month ordering in an `if` statements. How might I do this in your R package? 

I'm not that up on javascript, so I don't know how I might embed this technique in my markdown file. Any advice would be much appreciated.
 
```javascript
<script type="text/javascript">
        google.load("visualization", "1", {packages:["corechart", "charteditor"]});
        $(function () {

            var dateFormat =       $.pivotUtilities.derivers.dateFormat;
            var sortAs =           $.pivotUtilities.sortAs;
            var tpl =              $.pivotUtilities.aggregatorTemplates;
            var renderers =        $.pivotUtilities.renderers;
            var gchart_renderers = $.pivotUtilities.gchart_renderers

            $.get("montreal_2014.csv", function(montreal_2014) {
                $("#output").pivotUI($.csv.toArrays(montreal_2014), {

                    aggregators: {
                        "Mean Temp (Celcius)":  
                            function() { return tpl.average()(["Mean Temp (C)"])},
                        "Max Temp (Celcius)":   
                            function() { return tpl.max()(["Max Temp (C)"]) },
                        "Min Temp (Celcius)":   
                            function() { return tpl.min()(["Min Temp (C)"]) },
                        "Total Rain (mm)": 
                            function() { return tpl.sum()(["Total Rain (mm)"]) },
                        "Total Snow (cm)": 
                            function() { return tpl.sum()(["Total Snow (cm)"]) }
                    },
                    derivedAttributes: {
                        "year":       dateFormat("Date", "%y", true),
                        "month":      dateFormat("Date", "%m", true),
                        "day":        dateFormat("Date", "%d", true),
                        "month name": dateFormat("Date", "%n", true),
                        "day name":   dateFormat("Date", "%w", true)
                    },

                    sorters: function(attr) {
                        if(attr == "month name") {
                            return sortAs(["Jan","Feb","Mar","Apr", "May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]);
                        }
                        if(attr == "day name") {
                            return sortAs(["Mon","Tue","Wed", "Thu","Fri","Sat","Sun"]);
                        }
                    },

                    hiddenAttributes: ["Date","Max Temp (C)","Mean Temp (C)","Min Temp (C)" ,"Total Rain (mm)","Total Snow (cm)"],

                    renderers: $.extend(renderers, gchart_renderers),

                    rows: ["year", "month name"],
                    cols: ["day name"]


                });
            });
        });
    </script>

**Comment by smartinsightsfromdata** [comment]
@steventroysimpson 
It would be useful if you could show me a data example to better understand what you are aiming for.

Anyway, I haven't implemented the data formatter available in pivottable. If you look through pivottable issues, you'll see that the issue of dates is not straightforward - but probably you know it already from your R experience :)
I am very reluctant to add very complex code that most probably would not fully address the problem.

In general I suggest to use the old and tried methods:
- prefix months by a numerical value as: 01-Jan 02-Feb  etc.
- etc. for weeks / quarters.

**Comment by smartinsightsfromdata** [comment]
@steventroysimpson let me know if I can close this (I'll close it unless I hear from you in the next couple of days).

**Comment by steventroysimpson** [comment]
Close it. There's no resolution but it's not ur problem. Thnx


~ Steve

Sent via telepathy

**Comment by smartinsightsfromdata** [comment]
thanks

**Comment by smartinsightsfromdata** [comment]
@steventsimpson the current implementation has got a sorter now, working in a similar way to what you wanted.  Apologies it took so long.

**Comment by steventsimpson** [comment]
Thnx!


~ Steve

Sent via telepathy
