### ISSUE TITLE
No scrolling in large pivottable

### ISSUE THREAD

**Issue by pangleafrancis** [smartinsightsfromdata/rpivotTable#19]
When I create a pivottable with a lot of rows / columns, It is not possible to scroll.  I tested this in rstudio and in shiny.  Result is the same;

**Comment by smartinsightsfromdata** [comment]
@pangleafrancis could you kindly post a reproducible example, maybe with the diamonds dataset?

**Comment by pangleafrancis** [comment]
On Wed, Apr 22, 2015 at 2:20 PM, Enzo <notifications@github.com> wrote:

> diamonds

Hmmm...  It seems to work under shiny but not under shinydashboard.  It
might be a bug in that package.  Could you have a look anyway?

Thx,
Tom


ui.R

# This is the user-interface definition of a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)
library(shinydashboard)

dashboardPage(

  # Application title
  dashboardHeader(title = "Data Profiler"),

  # Sidebar with a slider input for number of bins
    # Show a plot of the generated distribution
  dashboardSidebar(),
  dashboardBody(

      rpivotTableOutput("test")
    )
)



# This is the server logic for a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#²

library(shiny)

shinyServer(function(input, output) {

  output$test <- rpivotTable::renderRpivotTable({
    rpivotTable(data = diamonds)

  })

})

-- 
*Tom Francis*
Francis Consulting BVBA
Hoveniersstraat 24
2840 Rumst
+32 473 273 057

**Comment by smartinsightsfromdata** [comment]
@pangleafrancis See [here](https://github.com/rstudio/shinydashboard/issues/8)

This works:

```R
library(shiny)
library(shinydashboard)
library(rpivotTable)
library(ggplot2)

data(diamonds)

header <- dashboardHeader(title = "Data Profiler")

sidebar <- dashboardSidebar()
  
body <- dashboardBody(
  tags$head(tags$style(
    type = 'text/css',
    '#test{ overflow-x: scroll; }'
  )),
  rpivotTableOutput("test")
  )


shinyApp(
  ui = dashboardPage(
    header, sidebar, body),
  server = function(input, output) {
    
    output$test <- rpivotTable::renderRpivotTable({
      rpivotTable(data = diamonds)
    })
    
  }
)

```

**Comment by pangleafrancis** [comment]
On Fri, Apr 24, 2015 at 12:07 AM, Enzo <notifications@github.com> wrote:

> tags$head(tags$style( type = 'text/css', '#test{ overflow-x: scroll; }'
> )),


Thanks!

Height however seems to be about half of the page now.  I have tried
several different css options, but he does not seem to accept the height
property.  Could you give pointers on where to look?

thanks again,
Tom


-- 
*Tom Francis*
Francis Consulting BVBA
Hoveniersstraat 24
2840 Rumst
+32 473 273 057

**Comment by smartinsightsfromdata** [comment]
@pangleafrancis Try:
```R
  rpivotTableOutput("test",height = "520px")
```

```"520px"``` is the maximum you can go in shinydashboard without breaking alignment with the other components. If you need more, or more flexibility in length, I would consider whether shinydashboard is the right approach, vs vanilla shiny.

**Comment by pangleafrancis** [comment]
On Fri, Apr 24, 2015 at 12:33 PM, Enzo <notifications@github.com> wrote:

> rpivotTableOutput("test",height = "520px")
>
>
Works perfectly.  Thanks!


-- 
*Tom Francis*
Francis Consulting BVBA
Hoveniersstraat 24
2840 Rumst
+32 473 273 057

**Comment by smartinsightsfromdata** [comment]
For potential users of `rpivotTable` (but the same, as I'm discovering, applies to other widgets) and `shinydashboard`, it is advisable to create a box with ad hoc `width` and `height`.

Then the box itself can be made scrollable:

```R
  box(title = "Pivot",width=8, height= 20, status = "primary", solidHeader = TRUE,
      tags$head(tags$style( type = 'text/css',  '#test{ overflow-x: scroll; }')),
  rpivotTableOutput("test")
)
```

**Comment by prokopyev** [comment]
Neither of above solutions seem to work nowadays.

**Comment by lalitsc12** [comment]
The dropdown menu get hidden under shinydashboard
![image](https://user-images.githubusercontent.com/45671202/97577320-a73d5b80-19c5-11eb-8153-19a03a816fab.png)
