### ISSUE TITLE
Issue displaying rpivott

### ISSUE THREAD

**Issue by arturochian** [smartinsightsfromdata/rpivotTable#2]
Hi @smartinsightsfromdata  I have this result when I use 
rpivotTable(data = dt, rows = "Party", cols = "Province", vals = "votes", aggregatorName = "Sum")

![image](https://cloud.githubusercontent.com/assets/4960935/6032361/23b61b16-abd6-11e4-9d93-32086a24e1c6.png)

I don't know if it's a new issue (this package is relatively new).

**Comment by arturochian** [comment]
I have this warning message

Warning message:
In FUN(X[[2L]], ...) :
  converting an R function to JSON as null. To change this, define a method for toJSON() for a 'function' object.

**Comment by arturochian** [comment]
R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=Spanish_Peru.1252 
[2] LC_CTYPE=Spanish_Peru.1252   
[3] LC_MONETARY=Spanish_Peru.1252
[4] LC_NUMERIC=C                 
[5] LC_TIME=Spanish_Peru.1252    

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] rpivotTable_0.1.2.3

loaded via a namespace (and not attached):
[1] devtools_1.7.0    digest_0.6.8     
[3] htmltools_0.2.6   htmlwidgets_0.3.2
[5] RJSONIO_1.3-0     tools_3.1.2      
[7] yaml_2.1.13

**Comment by smartinsightsfromdata** [comment]
Interesting.  Are you supplying data or using the example project?
I confess that currently example dataset does not contain "votes", so it is normal to expect it to give an error. 
I used "votes" in the README as an example of additive variable, but currently it is NOT in the dataset!.

But many thanks for this: it means (as I mention "votes" in the README as an example) that I need to add votes to avoid confusions.  I'll try to do it later today.

Thanks you again!

**Comment by smartinsightsfromdata** [comment]
I've just pushed an amendment of the library.  Now the dataset aligns to the example (e.g. you can set the sum of votes with
rpivotTable(data = jsdf_, rows = "Party", cols = "Province", vals = "votes", aggregatorName = "Sum")

**Comment by arturochian** [comment]
Hi @smartinsightsfromdata I reinstalled the package. However I have the same issue.

I tried with  data = jsdf_ and data = dt. 

I tried to find the data on the package.. where is it?

**Comment by arturochian** [comment]
I ran this and it worked :smile: 

https://github.com/smartinsightsfromdata/rpivotTable/blob/master/inst/examples/dat01.R
