### ISSUE TITLE
Upgrading to PivotTable.js 1.4.0

### ISSUE THREAD

**Issue by nicolaskruchten** [smartinsightsfromdata/rpivotTable#20]
FYI I just released a new version (1.4.0) of PivotTable.js which includes more C3 support, like a proper Area Chart and (finally) a Scatter Chart. I've also got an example of it where you can select any of the 700+ datasets that ship with R :)  http://nicolas.kruchten.com/pivottable/examples/rcsvs.html

**Comment by smartinsightsfromdata** [comment]
@nicolaskruchten I've upgraded to the 1.4.0  version. Thanks for the notification :)

**Comment by nicolaskruchten** [comment]
Great! Actually I released version 1.4.2 yesterday, which has a few nice charting fixes since 1.4.0 so I would recommend upgrading to that one. Should be the last release for the next little while :)

**Comment by smartinsightsfromdata** [comment]
@nicolaskruchten I think I've updated to 1.4.2 (i.e. this version of rpivottable is updated to the latest code commits).  May I suggest to put the release # in the README so that it becomes very visible?
I will make explicit reference to the pivottable release in the next version of rpivottable.

**Comment by nicolaskruchten** [comment]
OK great. Sorry about this, but I just found and fixed a bugin 1.4.2 (which affects charts with values between 0 and 1)  so I just pushed out 1.4.3. I recommend upgrading to 1.4.3 if at all possible.

**Comment by smartinsightsfromdata** [comment]
@nicolaskruchten No problem.  I'll do it later today.  Thanks!!
