### ISSUE TITLE
rpivotTable not rendering in Shiny

### ISSUE THREAD

**Issue by DangerCatTV** [smartinsightsfromdata/rpivotTable#21]
Just wanted to start by saying that this package is great! rpivotTable works so well within Rstudio - I'm just having some problems getting it to work with Shiny.

I'm using some of your code as a test (see below). The issue is that when I run the code a webpage appears but without the pivot table. I'm using R 3.2.0, shiny 0.11.1 and rpivotTable 0.1.3.5. I've tried uninstalling and then reinstalling everything but a pivot table still won't appear.

Has anyone else had shiny issues with rpivotTable 0.1.3.5? I think the issue could either be due to a problem in CSS (maybe it is creating a background in front of the table) or a version issue.

Any help would be amazing! Thanks.

library(shiny)
library(shinydashboard)
library(rpivotTable)
library(ggplot2)

data(diamonds)

header <- dashboardHeader(title = "Data Profiler")

sidebar <- dashboardSidebar()

body <- dashboardBody(
  tags$head(tags$style(
    type = 'text/css',
    '#test{ overflow-x: scroll; }'
  )),
  rpivotTableOutput("test")
)

shinyApp(
  ui = dashboardPage(
    header, sidebar, body),
  server = function(input, output) {
    
    output$test <- rpivotTable::renderRpivotTable({
      rpivotTable(data = diamonds)
    })
    
  }
)

rpivotTable(data = diamonds)

**Comment by happyshows** [comment]
version of htmlwidgets?

**Comment by DangerCatTV** [comment]
htmlwidgets_0.3.3

**Comment by happyshows** [comment]
I remember I have problem with the 0.3.3 for multiple packages based on htmlwidgets, because author switched to jsonlite. Can you try to install 0.3.2 from cran instead?

**Comment by smartinsightsfromdata** [comment]
I tried your code and it works fine on my laptop (no need for the "alone" rpivottable statement: as it is outside of shiny it will render in RStudio). 

@happyshows is correct: shiny and htmlwidgets need to be aligned, otherwise there will be problems (with any of the htmlwidgets, potentially).

Therefore, either you use CRAN version for both, or you use github version of both. Please let me know how it goes.

**Comment by DangerCatTV** [comment]
I'm not sure why shiny 0.11.1 wasn't working but I (literally just now) fixed the problem by upgrading to shiny 0.11.1.9004. Crazy that such a small thing could make such a big difference.

Thanks for all the help!
