### ISSUE TITLE
unable to change the width and height

### ISSUE THREAD

**Issue by panlanfeng** [smartinsightsfromdata/rpivotTable#23]
The width of line chart cannot be changed. Setting the `width` parameter  doesn't change anything.

**Comment by smartinsightsfromdata** [comment]
@panlanfeng not sure what you mean:  width in general changes the width of the widget.
On the other hand rpivotTable size is not "easily" confined to a particular size: it depends on the number of categories you have on columns or rows.
And, just to clarify, the way to change the width of  a line chart would changing css (if you really want to get into that...).

**Comment by panlanfeng** [comment]
How to set the width paramter?
My code is:

     iris %>%
     tbl_df %>%
     filter( Sepal.Width > 3 ) %>%
     rpivotTable(rows="Sepal.Length", cols="Sepal.Width", width="40%", rendererName="Scatter Chart")

and this doesn't change the width.

I am using it together with `knitr`. The chart can go out of screen. If change css, which file should I work on? Can you give a hint? I am not very familiar with css. Thanks!

**Comment by smartinsightsfromdata** [comment]
@panlanfeng I understand your issue better and I'm not sure that I have a solution for you.

See [here](https://github.com/smartinsightsfromdata/rpivotTable/issues/19) for a way to create a scrolling capability for rpivotTable within a precisely sized window (in the example shinydashboard).  Not sure if it will work with knitr (but please let me know if it does!).

**Comment by panlanfeng** [comment]
I was putting `rpivotTable` function within `knitr` chunk directly and the table was too large.
After I change to  `shinyApp(ui = ui, server = server)` approach as the [example](https://github.com/smartinsightsfromdata/rpivotTable/blob/6f04935f384fa1fec04d058b988c9f9ae9e91b22/inst/examples/canElections-shiny.R), it works well. 

Not yet tried to add scrolling capability. I will report the result here if I do.

**Comment by smartinsightsfromdata** [comment]
I will close this for now.  @panlanfeng  Let me know if you want me to re-open it.
