### ISSUE TITLE
Can't Install using Rstudio on PC running Windows 7

### ISSUE THREAD

**Issue by PKBibi** [smartinsightsfromdata/rpivotTable#26]
Can you help please.

I can't install rpivotTable on a windows 7 pc (RStudio Version 0.99.447).

Here is the output I get:

Installing htmlwidgets
Installing 1 packages: yaml
package ‘yaml’ successfully unpacked and MD5 sums checked
"C:/Program Files/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  "C:/Users/PK/AppData/Local/Temp/RtmpCEscPS/devtoolse6834c7b67/ramnathv-htmlwidgets-955ddc0"  \
  --library="C:/Users/PK/Documents/R/win-library/3.2" --install-tests 

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)

> install_github("smartinsightsfromdata/rpivotTable")
Downloading github repo smartinsightsfromdata/rpivotTable@master
Installing rpivotTable
Installing 1 packages: htmlwidgets
package ‘htmlwidgets’ successfully unpacked and MD5 sums checked
"C:/Program Files/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  "C:/Users/PK/AppData/Local/Temp/RtmpCEscPS/devtoolse682da67e74/smartinsightsfromdata-rpivotTable-89fcddf"  \
  --library="C:/Users/PK/Documents/R/win-library/3.2" --install-tests 

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)

Thanks in advance
PK

**Comment by smartinsightsfromdata** [comment]
@PKBibi  apologies for taking so long to reply.  Could you kindly try to install first of all **only** htmlwidgets (from CRAN) as a source?

```R
install.packages("htmlwidgets", type="source")
```

Once successful you can try as usual:

```R
devtools::install_github("smartinsightsfromdata/rpivottable")
```

The reason for this is to make sure you have all the proper tools in the windows environments and eliminate that as a cause of your issue.

**Comment by smartinsightsfromdata** [comment]
@PKBibi Any news on your problems? Can I close this issue? Thanks for letting me know

**Comment by smartinsightsfromdata** [comment]
Closing for now...

**Comment by PKBibi** [comment]
Hi Enzo

Apologies for not getting back to you earlier.

Yes you can close this.

I found out that because R was installed in "programs files" directory, I
could not install packages from github with devtools.

By un-installing R and re-installing in a separate directory (not the
default program files directory), this problem has been solved.

If you get this question a lot, perhaps ask them to check where they
installed R.

Once again, thanks for your assistance.

*BTW; where can I get the best intro tutorials to rpivotTable?*

Kind regards
PK Bibi

On Sun, Jul 12, 2015 at 4:15 PM, Enzo <notifications@github.com> wrote:

> Closing for now...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartinsightsfromdata/rpivotTable/issues/26#issuecomment-120728801>
> .
>



-- 
Kind regards

P. Bibi

**Comment by mariellasca** [comment]
Hello

can anyone help me with this errors? I cannot manage to install rpivotTable...Thanks

> install_github("ramnathv/htmlwidgets")

Downloading github repo ramnathv/htmlwidgets@master
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’

> devtools::install_github("smartinsightsfromdata/rpivottable")

Downloading github repo smartinsightsfromdata/rpivottable@master
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’

**Comment by smartinsightsfromdata** [comment]
@mariellasca have you tried to load the package ```stringi``` on its own first?

```stringi``` is used by a number of packages, including ```stringr```, which in turn is used by ```devtools``` etc..

R sometime does not seem to install dependencies (or is not doing it recursively), possibly when the Repo is not specified (see [here](http://stackoverflow.com/questions/14171148/how-to-tell-cran-to-install-package-dependencies-automatically)).

Let me know how it goes!

**Comment by mariellasca** [comment]
Yes, but that was not enough, I installed the last version of R and then it worked. Thanks
