### ISSUE TITLE
Cumulative sum?

### ISSUE THREAD

**Issue by Rustastra** [smartinsightsfromdata/rpivotTable#27]
Hi, I am not very good with JavaScript. Could you please help me create CumSum functionality? Thank you!

**Comment by smartinsightsfromdata** [comment]
@Rustastra I'm very sorry but rpivotTable works with the out-of-the-box aggregators in pivottable.
If you are using R you would be better off building CumSum in R and use either core functions (e.g. table) or external packages to display your results.

Alternative you could ask @nicolaskruchten to add CumSum to the (already very rich) number of aggregators available.

**Comment by smartinsightsfromdata** [comment]
Closing for now...
