### ISSUE TITLE
Rstudio hang after using sqldf package with rpivottable

### ISSUE THREAD

**Issue by maciejorlos** [smartinsightsfromdata/rpivotTable#28]
I am working on ubuntu 14.04 and  after putting such code:

    require(sqldf)
    require(rpivotTable)
    data(mtcars)
    rpivotTable(mtcars)
My rstudio hangs

**Comment by smartinsightsfromdata** [comment]
@maciejorlos it works for me on my OS X yosemite laptop.

I'm using ```RStudio```  0.99.467
Could you kindly post your ```sessionInfo()```?

Thanks

**Comment by smartinsightsfromdata** [comment]
@maciejorlos see #30: older versions of RStudio may cause problems.

**Comment by smartinsightsfromdata** [comment]
I'm closing it for now: I need proper sessionInfo() and a reproducible example.
