### ISSUE TITLE
too many to list

### ISSUE THREAD

**Issue by tvmanikandan** [smartinsightsfromdata/rpivotTable#31]
Hello,
When the Number of types/values for a variable I get the error "too many to list" when trying to select. Please help on this.

-Mani

**Comment by smartinsightsfromdata** [comment]
@tvmanikandan could you be so kind to publish a reproducible example? Thanks

**Comment by smartinsightsfromdata** [comment]
@tvmanikandan  can you post your ```sessionInfo()``` data?

Can you please check if you have the latest version of RStudio?

Apparently an older version (see #30) can create problems to the widget.

**Comment by smartinsightsfromdata** [comment]
I'm closing for now - until proper `sessionInfo()` and a reproducible example are available.
