### ISSUE TITLE
An error occurred rendering the PivotTable results.

### ISSUE THREAD

**Issue by songyurita** [smartinsightsfromdata/rpivotTable#33]
Hi,

Thanks for providing this great package. It works very well in Rstudio, however, when I want to use it in shiny, it gave me this error for chart:
An error occurred rendering the PivotTable results.

Pivot table was working but all the charts gave me the error. How can I fix it?

My code:
ui:
tabPanel("Daily Result",rpivotTableOutput("test"))

server:
 output$test <- renderRpivotTable({
   tt<-data.frame(c(1,2,3,4,1,2,3,4),c('a','b','c','d','c','d','a','b'))
   colnames(tt)<-c('x','y')
   re=rpivotTable(data=tt)
   re
 })

**Comment by songyurita** [comment]
nvm, I fixed it, it can't be used together with rchart nvd3

**Comment by smartinsightsfromdata** [comment]
@songyurita sometimes there are indeed conflicts related to the supporting libraries used in some of the widgets.  You should be safe using shiny of course is the first thing I check :) and the other htmlwidgets-based widgets, but anything else it may not work.
I have an open request on ggvis and shiny github issues for a jquery-ui incompatibility problem I'm currently having with ggis.

Maybe @ramnathv @jcheng5 @wch @yihui @timelyportfolio have ideas on how to make this more robust beyond the actual htmlwidgets?

(apologies for the "group call"!)

**Comment by smartinsightsfromdata** [comment]
@songyurita sadly no help so far.  I will close in two days if there is no further action requested.

**Comment by smartinsightsfromdata** [comment]
@songyurita  it seems that ggvis and shiny are going to converge very soon on a newer version on jquery-ui.  I'll keep you posted.  This should address this.

**Comment by wch** [comment]
FYI, the dev version of shiny and ggvis now have a full build of jQueryUI 1.11.4.

**Comment by smartinsightsfromdata** [comment]
@wch great stuff Winston!  Many thanks!
