### ISSUE TITLE
exclusions don't work with one column

### ISSUE THREAD

**Issue by langusta** [smartinsightsfromdata/rpivotTable#41]
Hi,
First of all, thank you for this wonderful package! I have a quite peculiar problem.
I'm trying to use `exclusions` parameter. When I add two columns from which I exclude certain values then everything works (you can see that names of columns are tilted):
![exclusions_two_cols](https://cloud.githubusercontent.com/assets/5746281/10906959/2d96b358-8226-11e5-89fc-d1a0d86dd32b.jpg)
If I use only one column then it doesn't:
![exclusions_one_col](https://cloud.githubusercontent.com/assets/5746281/10906964/3ef74bb2-8226-11e5-83a3-d5d128f2d6e0.jpg)

Code:
```R
rpivotTable(
   Titanic,
   rows = "Survived",
   cols = c("Class","Sex"),
   aggregatorName = "Sum as Fraction of Columns",
   exclusions = list(
                    Survived = as.list("No")
                    , 
                    Class = as.list("1st")
                     ),
   vals = "Freq",
   rendererName = "Table Barchart"
)
```
My session info:
```R
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=pl_PL.UTF-8       LC_NUMERIC=C               LC_TIME=pl_PL.UTF-8       
 [4] LC_COLLATE=pl_PL.UTF-8     LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=pl_PL.UTF-8   
 [7] LC_PAPER=pl_PL.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rpivotTable_0.1.5.8

loaded via a namespace (and not attached):
[1] htmlwidgets_0.5.1 htmltools_0.2.6   tools_3.2.2       rstudioapi_0.3.1 
[5] yaml_2.1.13       rstudio_0.98.1103 jsonlite_0.9.17   digest_0.6.8    
```

**Comment by MarcinKosinski** [comment]
+1

**Comment by smartinsightsfromdata** [comment]
I think it is a perverse effect of the auto_box Map in the code.

While I think of a cleverer way to address this, why don't you simply write:

````
rpivotTable(
  Titanic,
  rows = "Survived",
  cols = c("Class","Sex"),
  aggregatorName = "Sum as Fraction of Columns",
  inclusions = list(
    Survived = list("Yes")
    ,
    Class = list("1st","2nd", "3rd", "Crew")
  ),
  vals = "Freq",
  rendererName = "Table Barchart"
)
````

It works for me.

**Comment by MarcinKosinski** [comment]
@langusta maybe you could extend documentation with that example and provide a pull request to this repository?

**Comment by smartinsightsfromdata** [comment]
I've got a better way.  I'll try to integrate it into master tomorrow.

**Comment by smartinsightsfromdata** [comment]
Version  0.1.5.9 (now on github) allows single column inclusions / exclusions.

**Comment by langusta** [comment]
It works indeed. Thank you!
