### ISSUE TITLE
Make use of `overwrite` explicit?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [smartinsightsfromdata/rpivotTable#42]
@steadyfish @king23  I would appreciate your input (as well as the input of anybody else of course) as users of this package and especially of this functionality.

The way that `pivottable` makes the continuos programming of the pivot table possible is through a parameter called `overwrite`. In Nicolas words:

`overwrite` is a boolean defaulting to false which controls what happens if this function is called repeatedly on the same element. If set to true, the options object overwrites the current state of the UI. If set to false, only the input data set changes, and the state of the UI remains the same, unless this is the first call, at which point the UI will be set to the options 

In fact, to make `rpivotTable` programmable I simply "forced" a value of `true` for `overwrite` in the parameters list in the JS code.
In hindsight I sort of regret this approach, as prevents to do the opposite, sending different datasets keeping the metadata set constant.

Do you (or anybody else) see a problem if I bring this parameter into the `rpivotTable` calling parameter set, possibly as:

```
rpivotTable(
  Titanic,
  rows = "Survived",
  cols = c("Class","Sex"),
  aggregatorName = "Sum as Fraction of Columns",
  inclusions = list( Survived = list("Yes")),
  exclusions= list( Class = list( "Crew")),
  vals = "Freq",
  rendererName = "Table Barnhart",
 overwrite = TRUE
)
```

Probably to avoid to break existing working code the parameter default could be set to TRUE in any case.

Any comment is appreciate.

**Comment by King23** [comment]
Hi @smartinsightsfromdata, i did try to use both TRUE and FALSE overwrite in my code and i don't see any changes to my output. Can you  elaborate a bit more how this parameter affecting the output? Besides, what is the motivation that makes you think to change your current approach (forced TRUE) going to FALSE? thanks.

**Comment by steadyfish** [comment]
@smartinsightsfromdata makes sense. This would certainly help when working with multiple datasets (or even subsets of data).

Also, agree with your point on defaulting `overwrite = TRUE`.

**Comment by smartinsightsfromdata** [comment]
@King23 Apologies for the confusion: I still have to make the change!  I am just trying to have some suggestion before actually implementing it...

**Comment by King23** [comment]
@smartinsightsfromdata, thanks for clarification. If it is configurable (TRUE/FALSE), i would love to try it out once you made the change. :)

**Comment by smartinsightsfromdata** [comment]
I've currently abandoned this possibility.  Please let me know if anybody is interested in experimenting with it.
