### ISSUE TITLE
The 'rendererName' argument not working

### ISSUE THREAD

**Issue by GKyle23** [smartinsightsfromdata/rpivotTable#45]
Hi there,

I've noticed that the 'rendererName' doesn't work. There is no error thrown, it just always defaults to table no matter what renderer you select.

**Comment by smartinsightsfromdata** [comment]
@GKyle23 Apologies: it is a book crept into the CRAN submission at the last minute.  I am expecting any day a new version of pivottable that I'll integrate and re-submit to CRAN.

Till such time, would you be so kind to use the github version please?

**Comment by GKyle23** [comment]
OK great - thanks
