### ISSUE TITLE
How I set the number of decimal 

### ISSUE THREAD

**Issue by ThoDuyNguyen** [smartinsightsfromdata/rpivotTable#46]
I notice that currently 2-digit decimal is set as default. 
Is it possible that I could change this value?

Thank you in advance.

**Comment by pkopps** [comment]
I am also unclear on how to facilitate this

**Comment by smartinsightsfromdata** [comment]
If I understand @nicolaskrutchen answer (see below), it is not exactly an easy change, moreover any change (beside using the current `integer sum` if you want to display only integer values) would apply to the entire table.

See discussion here https://github.com/nicolaskruchten/pivottable/issues/559

Feel free to re-open if you have an idea on how to address this.
