### ISSUE TITLE
Remove limit of list Category

### ISSUE THREAD

**Issue by nickknauer1** [smartinsightsfromdata/rpivotTable#48]
I have created an rpivottable and for some of the factors that I want to drag and drop to create tables and graphs, they contain more than 500 factors. Is there a way to eliminate the limit of each factor so that when I click on any option in the pivottable, it will show me a list of the options and from there I can filter out what I want? Currently, when I click on the factors that have too large of a list, it states, "too large to list". And when I try and create the graphs, it doesn't work because there are too many factors.

**Comment by smartinsightsfromdata** [comment]
Sadly there isn't an overarching solution to this (you can consult the list of Frequently Asked Questions in the pivottable github page in Nicolas Krutchen pivottable page [here] (https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions) )

I can suggest the following trick though:

- Identify sub-categories  / sub-classes in the data dimensions that are "too large". If there in't any natural sub-division, you could use any relevant sub-class (e.g. letters of alphabet if the category as a whole is character based or a factor.
- Select first the appropriate subdivision for your analysis.

I know that the above "trick" will not work in every case, but it could help to address some of the most common cases.

**Comment by nickknauer1** [comment]
I actually found a solution to this. Below is the stackoverflow answer: 

http://stackoverflow.com/questions/34793135/rpivottable-being-able-to-list-more-than-allowable-amount/34895345#34895345

**Comment by smartinsightsfromdata** [comment]
@nickknauer1 

Thanks and congrats!  I don't know of this possibility myself.

I post it here the solution for future reference:

```
tmp <- rbind(iris, iris)
# Here you have limit on num column:
rpivotTable(cbind(tmp, num = 1:dim(tmp)[1]))
# Here you don't:
rpivotTable(cbind(tmp, num = 1:dim(tmp)[1]), menuLimit = 500)
```
