### ISSUE TITLE
Using `derivedAttributes` parameter

### ISSUE THREAD

**Issue by steadyfish** [smartinsightsfromdata/rpivotTable#49]
Hi,

I am trying to use `derivedAttributes` parameter but haven't been successful. Is it supported in the current version? Could you share an example if it is?

Here's the example I tried - 

```
library(htmlwidgets)
library(rpivotTable)

df = data.frame(a = 1:10, b = 11:20)

my_func = JS("var c = function(record) {
    return record.a / record.b;
   }")

rpivotTable(df, derivedAttributes = my_func)
```

In the browser console I see this error - 

> SyntaxError: expected expression, got keyword 'var'
> window.HTMLWidgets.evaluateStringMember()         htmlwidgets.js:638
> window.HTMLWidgets.staticRender/</<()                   htmlwidgets.js:532
> forEach()                                                                     self-hosted:216
> forEach()                                                                     htmlwidgets.js:55
> window.HTMLWidgets.staticRender/<() htmlwidgets.js:466
> forEach() self-hosted:216
> forEach() htmlwidgets.js:55
> window.HTMLWidgets.staticRender() htmlwidgets.js:464
> <anonymous> htmlwidgets.js:544

**Comment by Jiang-Li** [comment]
I also want to know this. Any idea from the developers?

**Comment by smartinsightsfromdata** [comment]
same issue as #54 

I am not entirely sure of the advantage of doing this within rpivotTable.
R allows to add any type of attribute very easily. Why would you do it on the client in JavaScript?

This "ease of use" is not exactly there in javascript, hence the effort of @nicolaskruchten to add derived attributes.  I do not dismiss derived attributes, but I do not see presently their value from an R ecosystem point of view. Awaiting to be convinced :)

**Comment by steadyfish** [comment]
A usecase - When trying to show any statistic other than Simple Average over different groups say variance or median or mode.

Perhaps can also be achieved by writing a custom aggregator?

**Comment by smartinsightsfromdata** [comment]
@steadyfish  a custom aggregator could be an ideal solution for a `javascript` project. In our case I'm not so sure.

Let's not forget that so far `rpivotTable` takes a standard release from `pivottable` & wraps it around for R...

Keen to hear others' comments...

**Comment by nicolaskruchten** [comment]
FWIW I feel like the Javascript derived attribute mechanism is a bad fit for the R wrapper. R's ability to mutate and manipulate data frames is so much more powerful than the derived attribute feature of PivotTable.js that I would recommend just adding a column to the data frame before calling the pivot table :)

**Comment by martinlarsen** [comment]
Please, I would like to use rPivotTable to apply a user defined aggregator function, or simply base median(), for various subsets of a dataframe. Can anyone please show an example code. I have tried this:

df <- data.frame(A=c(1:10),B=c(-10:-1),C=c(21:30))
rpivotTable(data=df, rows="A", col="B", aggregator=median(), aggregatorName="Median")

Great wrapper, but difficult to understand the full set of parameter attributes.

**Comment by smartinsightsfromdata** [comment]
@martinlarsen I struggle to understand why you would need to use a user defined aggregator when you can use the freedom of `R` to define *any* custom aggregator you need. 

As in `R` you can even add or delete columns programmatically, I do not currently see the limitation.

Care to explain you use case please?

**Comment by martinlarsen** [comment]
Hi, 
Sorry if I was not sufficiently clear. My situation is that I work with biological data where we often have many variables but not that many samples. Performing statistics on this type of data requires non-parametric tests. In other words median rather than mean etc. The pivot table provided in Microsoft Excel allows only to apply some pre-configured aggregators (excluding median). I therefore use the aggregate function in R to calculate median values (and other aggregator functions) for various subsets of data. The idea for me was to use rPivotTable for data mining without requiring to reprogram the aggregate command. I was working on a Shiny application that would ease my work, when I stumbled over rPivotTable. It is really well done and I would like to use this rather than having to make it myself, but I really need to be able to insert my own Aggregator. 

Finally, it would really be useful to be able to include summaries, which are not the sum of entries, but rather statistical comparisons between groups (Mann-Whitney versus Kruskal-Wallis depending on the number of groups for non-parametric and similar for parametric tests). 

However, just enabling manual aggregators would already be a big step on the way. 

I thank you very much for having gone through the trouble of creating this great tool.

**Comment by martinlarsen** [comment]
You write that you don't understand my need, since I can use the freedom of R to define any custom aggregator function. If this is indeed the case, could you please write an example code of how you implement this. E.g. using the median as aggregator. See my example from my previous post, which doesn't work in my hands. It is very likely that I'm asking something which is already supported, and it is simply me not doing the right thing.

**Comment by nicolaskruchten** [comment]
I think that median would be an eminently reasonable addition to the
underlying JavaScript library (of which I am the maintainer), but I'm not
sure if the group comparison ones make sense there. I can see the case for
more sophisticated aggregators though.

Other than the median, what other general purpose aggregators make sense
here? Variance?

**Comment by smartinsightsfromdata** [comment]
Let's see, first of all, if I've got the `pipeline` you have in mind right.

Let's assume to have a csv with the following data:

```
Employees	Sales Cycle Days
21 to 30	91
6 to 10	60
6 to 10	174
1 to 5	3
1 to 5	24
Over 30	276
1 to 5	251
11 to 15	298
1 to 5	145
Over 30	35
1 to 5	180
1 to 5	63
21 to 30	184
1 to 5	55
1 to 5	103
1 to 5	34
6 to 10	36
16 to 20	41
16 to 20	50
```

And this is the `R` code I've come up with:

```
library(rpivotTable)

df <- read.csv(file='./median.csv', stringsAsFactors = F)
table(df)

dfa <- aggregate(. ~ Employees, data=df, FUN = median)

rpivotTable(dfa, rows=c('Employees'), vals='Sales.Cycle.Days', aggregatorName="Sum")
```

As you can see I've selected `Sum` as an aggregator, but `Max` or `Min` would have worked the same.

But if this is the use case, I would rather use `DT` in shiny or `table` in base `R`.

Is this what we are talking about?

**Comment by nicolaskruchten** [comment]
@smartinsightsfromdata this is sort of cheating though, you're pre-aggregating before putting the data into the pivot table... I think what's desired here is a way to just call `rpivotTable` and then get a table of medians as you drag and drop.

If we wanted to use the full power of R here, we would need a special Javascript-side aggregator that just accumulates values and then calls back to R code for aggregation. Then you could use any R built-in on the fly.

**Comment by steadyfish** [comment]
In the essence the requirement is to have [OLAP](https://en.wikipedia.org/wiki/Online_analytical_processing) like functionality in `rpivotTable`..

**Comment by nicolaskruchten** [comment]
Arguably all pivot tables provide OLAP functionality :)

It sounds like you just want a few more JavaScript-side aggregators like
median, mode, stdev, var etc, all of which are pretty to implement. What is
much harder to build is a bridge between PivotTable.js and arbitrary R
aggregators.

**Comment by martinlarsen** [comment]
Indeed, you have understood what I'm looking for. I wish to avoid using aggregate to be able to change the variables to aggregate over by drop and drag in a pivot table. Indeed, most of my needs could be accommodated with a few standard aggregators, although i think a custom aggregator would be really great. The most important aggregator that I would like is median, but standard deviation, standard error, 25% and 75% quartiles, variance, entropy measures (shannon index etc.)  would also be of interest. Just like in excel it should be possible to include in the final table multiple aggregators (median along with measures of variation, such as 25-75% quartiles).

**Comment by nicolaskruchten** [comment]
Quick response re multiple aggregators: unfortunately this will likely
never be a supported feature of PivotTable.js, given the UX challenges and
scale of the rewrite necessary to support them.

Regarding additional aggregators, I would be open to adding some of these
to PivotTable.js, possibly as an optional extension for the more exotic
ones, such that rpivotTable could make use of them.

**Comment by smartinsightsfromdata** [comment]
@nicolaskruchten  Additional aggregators would be really good.

Frankly I have some reservation on the 'bridge' between `R` and `pivottable.js`.  

We have currently the ability of exporting data out of the pivottable, which is great.  

But to have a sort of ping pong between `R` and `pivottable.js` seems to open any sort of issues (including the potential for races etc.).

**Comment by nicolaskruchten** [comment]
I understand and respect your concerns about the R/JS bridge, for I have
the same ones about the sometimes-requested Py/JS bridge in the
jupyter_pivottable integration :)

People often ask about server-side integration for PivotTable.js
computation in a web context as well, which boils down to the same issue
technically and I've generally decided that this is out of scope for the
moment given the architecture of the library.

**Comment by nicolaskruchten** [comment]
@martinlarsen @steadyfish I'm curious: would you use 'population' or 'sample' variance/stdev more often? Both Excel and Google Sheets support both (var, varp, stdev, stdevp) which I've always found unpleasant, but I understand the differences.

**Comment by martinlarsen** [comment]
I use "sample" statistics as we never analyze all possible samples of a given population (e.g. we don't analyze all the patients with a given disease, but rather a small hopefully representative subset). Maybe in other areas population statistics would be relevant, but I don't think it is the case in biology (at least not in the contexts I have been in touch with).

**Comment by martinlarsen** [comment]
In addition, I want to underline that supporting non-parametric statistics, such as median and 25%-75% quartiles would be a major advance compared to Excel. This is an important lack in Excel recognized by many biologists (and other scientists with small sample size requiring non-parametric analysis).

**Comment by timelyportfolio** [comment]
### [`simple-statistics`](http://simplestatistics.org/docs/) as aggregator

I have intended to demonstrate this for a while, and I'll use the v4 release of @tmcw [`simple-statistics`](http://simplestatistics.org/docs/) as a motivation to post some code to show integration of the additional descriptive statistics from `simple-statistics` in `rpivotTable` or really `pivottable` in general.


### example with code

While I am sure the next request will be the entire suite of descriptive statistics, I'll keep the demo small with just an example of `quantile([], 0.25)`.  We could easily build a small repo for a plugin a fuller set.

```
library(dplyr)
library(htmlwidgets)
library(rpivotTable)
library(htmltools)


rpvt <- rpivotTable(
  mtcars,
  aggregators = htmlwidgets::JS('{ss_quantile25: ss_quantile25()}')
)

# rpivotTable auto boxes everything except inclusions and exclusions
#  https://github.com/smartinsightsfromdata/rpivotTable/blame/master/R/rpivotTable.R#L110-L117
#  so we need to unbox or unlist
rpvt$x$params$aggregators <- rpvt$x$params$aggregators[[1]]


tagList(
  tags$script(src = "https://unpkg.com/simple-statistics@4.0.0/dist/simple-statistics.min.js"),
  tags$script(
"
library(dplyr)
library(htmlwidgets)
library(rpivotTable)
library(htmltools)


rpvt <- rpivotTable(
  mtcars,
  aggregators = htmlwidgets::JS('{ss_quantile25: ss_quantile25()}')
)

# rpivotTable auto boxes everything except inclusions and exclusions
#  https://github.com/smartinsightsfromdata/rpivotTable/blame/master/R/rpivotTable.R#L110-L117
#  so we need to unbox or unlist
rpvt$x$params$aggregators <- rpvt$x$params$aggregators[[1]]


tagList(
  tags$script(src = "https://unpkg.com/simple-statistics@4.0.0/dist/simple-statistics.min.js"),
  tags$script(
"
var ss_quantile25 = function(formatter) {
  if (formatter == null) {
    formatter = $.pivotUtilities.numberFormat();
  }
  return function(arg) {
    var attr;
    attr = arg[0];
    return function(data, rowKey, colKey) {
      return {
        arr: [],
        push: function(record) {
          if (!isNaN(parseFloat(record[attr]))) {
            this.arr.push(parseFloat(record[attr]));
          }
        },
        value: function() {
          return this.arr.length ? ss.quantile(this.arr, 0.25) : null;
        },
        format: formatter,
        numInputs: attr != null ? 0 : 1
      };
    };
  };
}
"
  ),
  rpvt
) %>%
  browsable()
```

### screenshot

Below is a screenshot of the result.  You might notice slight differences in the R `quantile` and the `simple-statistics` quantile.

![image](https://cloud.githubusercontent.com/assets/837910/25408587/3eceb45c-29d4-11e7-99a3-5decf82e99fa.png)

**Comment by timelyportfolio** [comment]
One more for fun adding `median`.

```
library(dplyr)
library(htmlwidgets)
library(rpivotTable)
library(htmltools)


rpvt <- rpivotTable(
  mtcars,
  aggregators = htmlwidgets::JS('{ss_quantile25: ss_quantile25(), median: median()}')
)

# rpivotTable auto boxes everything except inclusions and exclusions
#  https://github.com/smartinsightsfromdata/rpivotTable/blame/master/R/rpivotTable.R#L110-L117
#  so we need to unbox or unlist
rpvt$x$params$aggregators <- rpvt$x$params$aggregators[[1]]


tagList(
  tags$script(src = "https://unpkg.com/simple-statistics@4.0.0/dist/simple-statistics.min.js"),
  tags$script(
"
var ss_quantile25 = function(formatter) {
  if (formatter == null) {
    formatter = $.pivotUtilities.numberFormat();
  }
  return function(arg) {
    var attr;
    attr = arg[0];
    return function(data, rowKey, colKey) {
      return {
        arr: [],
        push: function(record) {
          if (!isNaN(parseFloat(record[attr]))) {
            this.arr.push(parseFloat(record[attr]));
          }
        },
        value: function() {
          return this.arr.length ? ss.median(this.arr, 0.25) : null;
        },
        format: formatter,
        numInputs: attr != null ? 0 : 1
      };
    };
  };
}

var median = function(formatter) {
  if (formatter == null) {
    formatter = $.pivotUtilities.numberFormat();
  }
  return function(arg) {
    var attr;
    attr = arg[0];
    return function(data, rowKey, colKey) {
      return {
        arr: [],
        push: function(record) {
          if (!isNaN(parseFloat(record[attr]))) {
          this.arr.push(parseFloat(record[attr]));
          }
        },
        value: function() {
          return this.arr.length ? ss.median(this.arr) : null;
        },
        format: formatter,
        numInputs: attr != null ? 0 : 1
      };
    };
  };
};
"
  ),
  rpvt
) %>%
  browsable()
```

### screenshot

![image](https://cloud.githubusercontent.com/assets/837910/25408924/7ce59304-29d5-11e7-9ae4-9624c8b66f60.png)

**Comment by smartinsightsfromdata** [comment]
@timelyportfolio  It looks great - and it is worth documenting it properly.  I assume that this may cover some of the more esoteric cases mentioned in this thread?

But for ease of use  I still hope that @nicolaskruchten will implement some standard aggregators :)

**Comment by martinlarsen** [comment]
Thanks a lot for this solution. I agree with Enzo. Would be great to have this solution documented (which other functions are available in this manner - ss_????). Better yet, would be to have it implemented in a standardized manner in the rPivotTable package. I tried out the last solution including both Median and Quantile, and I realized that the Quantile_25 function was erroneously set as the median. Here I include an updated and corrected version, which includes the Quantile_75 function as well.

```
library(dplyr)
library(htmlwidgets)
library(rpivotTable)
library(htmltools)

rpvt <- rpivotTable(
  mtcars,
  aggregators = htmlwidgets::JS('{median: median(), ss_quantile25: ss_quantile25(), ss_quantile75: ss_quantile75()}')
)

# rpivotTable auto boxes everything except inclusions and exclusions
#  https://github.com/smartinsightsfromdata/rpivotTable/blame/master/R/rpivotTable.R#L110-L117
#  so we need to unbox or unlist
rpvt$x$params$aggregators <- rpvt$x$params$aggregators[[1]]


tagList(
  tags$script(src = "https://unpkg.com/simple-statistics@4.0.0/dist/simple-statistics.min.js"),
  tags$script(
    "
    var median = function(formatter) {
    if (formatter == null) {
    formatter = $.pivotUtilities.numberFormat();
    }
    return function(arg) {
    var attr;
    attr = arg[0];
    return function(data, rowKey, colKey) {
    return {
    arr: [],
    push: function(record) {
    if (!isNaN(parseFloat(record[attr]))) {
    this.arr.push(parseFloat(record[attr]));
    }
    },
    value: function() {
    return this.arr.length ? ss.median(this.arr) : null;
    },
    format: formatter,
    numInputs: attr != null ? 0 : 1
    };
    };
    };
    };

    var ss_quantile25 = function(formatter) {
    if (formatter == null) {
    formatter = $.pivotUtilities.numberFormat();
    }
    return function(arg) {
    var attr;
    attr = arg[0];
    return function(data, rowKey, colKey) {
    return {
    arr: [],
    push: function(record) {
    if (!isNaN(parseFloat(record[attr]))) {
    this.arr.push(parseFloat(record[attr]));
    }
    },
    value: function() {
    return this.arr.length ? ss.quantile(this.arr, 0.25) : null;
    },
    format: formatter,
    numInputs: attr != null ? 0 : 1
    };
    };
    };
    }

    var ss_quantile75 = function(formatter) {
    if (formatter == null) {
    formatter = $.pivotUtilities.numberFormat();
    }
    return function(arg) {
    var attr;
    attr = arg[0];
    return function(data, rowKey, colKey) {
    return {
    arr: [],
    push: function(record) {
    if (!isNaN(parseFloat(record[attr]))) {
    this.arr.push(parseFloat(record[attr]));
    }
    },
    value: function() {
    return this.arr.length ? ss.quantile(this.arr, 0.75) : null;
    },
    format: formatter,
    numInputs: attr != null ? 0 : 1
    };
    };
    };
    }
    "
  ),
  rpvt
) %>%
  browsable()
```

**Comment by timelyportfolio** [comment]
@smartinsightsfromdata, I happen to believe that this is well within our capabilities and that this would be an excellent opportunity to contribute to the wonderful `pivottable` project on which we rely.  Expecting more of @nicolaskruchten at this point given his very admirable and appreciated ongoing commitment seems unreasonable.

The pattern illustrated above is simple and straightforward.  We just need to wrap all the obvious functions in a small JS plugin, and we are done, and the whole community benefits.

As an example of a two attribute formula (actually correlation is better as one attribute with long data), here is correlation with wide data.

```r
library(dplyr)
library(htmlwidgets)
library(rpivotTable)
library(htmltools)
library(PerformanceAnalytics)

data(managers)

rpvt <- rpivotTable(
  data.frame(
    date = as.numeric(format(index(managers),"%Y")),
    managers,
    stringsAsFactors = FALSE
  )[,c(1,2,4,5,9,10,11)],
  aggregators = htmlwidgets::JS('{ss_quantile25: ss_quantile25(), ss_median: median(), ss_correlation: correlation()}')
)

# rpivotTable auto boxes everything except inclusions and exclusions
#  https://github.com/smartinsightsfromdata/rpivotTable/blame/master/R/rpivotTable.R#L110-L117
#  so we need to unbox or unlist
rpvt$x$params$aggregators <- rpvt$x$params$aggregators[[1]]


tagList(
  tags$script(src = "https://unpkg.com/simple-statistics@4.0.0/dist/simple-statistics.min.js"),
  tags$script(HTML(
"
var ss_quantile25 = function(formatter) {
  if (formatter == null) {
    formatter = $.pivotUtilities.numberFormat();
  }
  return function(arg) {
    var attr;
    attr = arg[0];
    return function(data, rowKey, colKey) {
      return {
        arr: [],
        push: function(record) {
          if (!isNaN(parseFloat(record[attr]))) {
            this.arr.push(parseFloat(record[attr]));
          }
        },
        value: function() {
          return this.arr.length ? ss.quantile(this.arr, 0.25) : null;
        },
        format: formatter,
        numInputs: attr != null ? 0 : 1
      };
    };
  };
}

var median = function(formatter) {
  if (formatter == null) {
    formatter = $.pivotUtilities.numberFormat();
  }
  return function(arg) {
    var attr;
    attr = arg[0];
    return function(data, rowKey, colKey) {
      return {
        arr: [],
        push: function(record) {
          if (!isNaN(parseFloat(record[attr]))) {
          this.arr.push(parseFloat(record[attr]));
          }
        },
        value: function() {
          return this.arr.length ? ss.median(this.arr) : null;
        },
        format: formatter,
        numInputs: attr != null ? 0 : 1
      };
    };
  };
};

var correlation = function(formatter) {
  if (formatter == null) {
    formatter = $.pivotUtilities.numberFormat();
  }
  return function(arg) {
    var attrX, attrY;
    attrX = arg[0];
    attrY = arg[1];
    
    return function(data, rowKey, colKey) {
      return {
        arrX: [],
        arrY: [],
        push: function(record) {
          if (!isNaN(parseFloat(record[attrX]))) {
            this.arrX.push(parseFloat(record[attrX]));
          }
          if (!isNaN(parseFloat(record[attrY]))) {
            this.arrY.push(parseFloat(record[attrY]));
          }
        },
        value: function() {
          return this.arrX.length && this.arrY.length ? ss.sampleCorrelation(this.arrX, this.arrY) : null;
        },
        format: formatter,
        numInputs: (attrX != null) && (attrY != null) ? 0 : 2
      };
    };
  };
};
"
  )),
  rpvt
) %>%
  browsable()
```

**Comment by smartinsightsfromdata** [comment]
@timelyportfolio can you kindly clarify your plan?

Do you intend to submit a PR to `pivottable`, or you think better to submit a PR to `rpivotTable`?

Obviously I'm fine with both proposals.

**Comment by nicolaskruchten** [comment]
@timelyportfolio thank you for your kind words :)

I've just pushed a branch (https://github.com/nicolaskruchten/pivottable/compare/stats) which adds aggregator *templates* for quantiles and running variance/stdev calculations. These templates a flexible enough to build out aggregators for medians and other quantiles, as well as sample or population variance or standard deviation. I've used them to add median, sample variance and sample standard deviation to the `en` locale. I used a neat one-pass variance algorithm as per Knuth: https://www.johndcook.com/blog/standard_deviation/

Please take a look and let me know if this would meet your needs. I think at the level of this `rpivotTable` project you will need to choose whether or not to add other quantiles to your default aggregator set, as well as deciding if you also want the 'population' variant of variance and standard deviation. Also, clearly this branch doesn't address the more exotic aggregators that serious statisticians might want, so there is still likely a place for some simple-statistics-based fun :)

**Comment by timelyportfolio** [comment]
Thanks so much @nicolaskruchten for your very admirable commitment to such a fine library!  Not sure if you saw this geo pivot table example using turf.js https://bl.ocks.org/timelyportfolio/f9dbdf77c37ff9d2c3b81967819231ff.

Would you be interested in a `simple-statistics` plugin for pivottable if we were willing to do the work?

**Comment by nicolaskruchten** [comment]
I did see your geo mashup on Twitter, and although it doesn't scratch any itches I have in my work, it might have some legs yet ;)  Perhaps implementing it as a renderer would make it more usable/user-friendly, so that the JSON doesn't appear in the table?

re simple-statistics, there are definitely a bunch of functions in there that some people would find useful, so I would welcome a PR into the main pivottable repo which contained, for example, a `simple_statististics_aggregators.coffee` file and an example HTML file which showed how to use it, perhaps using the existing Montreal Weather 2014 dataset?

**Comment by nicolaskruchten** [comment]
OK, I've just pushed version 2.12.0 which contains these upgrades

**Comment by nicolaskruchten** [comment]
Annnnd just pushed 2.13.0 which contains bugfixes for these upgrades :)

**Comment by smartinsightsfromdata** [comment]
I will resubmit in a week time.  Many thanks!

**Comment by ShuSir** [comment]
Hi @smartinsightsfromdata just to check will the enhancement available be available soon? 
Again thanks for your wonderful work !

**Comment by smartinsightsfromdata** [comment]
@ShuSir library is update to latest pivotable.

Closing this issue now.
