### ISSUE TITLE
Interavtivity with shinyFiles

### ISSUE THREAD

**Issue by njburgoyne** [smartinsightsfromdata/rpivotTable#52]
Hi, great package, I have used it to great effect in a data explorer in our company. So good it was that I have started using it in a second project. Alongside the (multiple) file uploader package shinyFiles (find it on CRAN). 

ShinyFiles uses htmlWidgets to pass information between the server and ui. Where one of the htmlWidgets javascript files calls the renderValue js function. Unfortunatly rpivotTable.js also has a function called renderValue() and this is where things go wrong. There appears to be cross talk which means that I can't upload multiple files and use rpivotTable in the same shiny app. 

Given the number of dependencies, it might be easier to change rpivotTable than htmlWidgets, is this change possible?

Thanks again

(PS I have removed a coluple of company-speciic packages from the sessionInfo())

**Example Script**

```R
library(shiny)
library(rpivotTable)
library(shinyFiles)

# Define server logic required to draw a histogram
server <- function(input, output, session){
  #volumes <- getVolumes()
  volumes <- c(`Local (C)`="C:", 
               `Data (M)`="M:")
  shinyFileChoose(input = input, 
                  id = 'file', 
                  roots = volumes, 
                  session = session)
  output$filepaths <- renderPrint({parseFilePaths(volumes, input$file)})
  output$bPivotTable <- renderRpivotTable({
    rpivotTable(data = iris)
  })
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
        fluidRow(strong("Choose files to upload:")),
        fluidRow(
          shinyFilesButton(id = "file", 
                           label = "Files", 
                           title = "Upload Files",
                           multiple = TRUE)
        )
    ),
    mainPanel(
      verbatimTextOutput('filepaths'), 
      rpivotTableOutput("bPivotTable")  
    )
  )
)

print(shinyApp(ui = ui, server = server))
```

**Session Info**

R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] stringr_1.0.0        lme4_1.1-12          Matrix_1.2-6         ggplot2_2.1.0    reshape2_1.4.1      
 [8] readxl_0.1.1         RODBC_1.3-13         leaflet_1.0.1        lubridate_1.5.6      rpivotTable_0.1.5.20 shiny_0.13.2         shinyFiles_0.6.0    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5      magrittr_1.5     MASS_7.3-45      munsell_0.4.3    lattice_0.20-33  colorspace_1.2-6 xtable_1.8-2     R6_2.1.2        
 [9] minqa_1.2.4      plyr_1.8.4       tools_3.3.0      grid_3.3.0       nlme_3.1-127     gtable_0.2.0     htmltools_0.3.5  yaml_2.1.13     
[17] digest_0.6.9     RJSONIO_1.3-0    nloptr_1.0.4     htmlwidgets_0.6  mime_0.4         stringi_1.1.1    scales_0.4.0     jsonlite_0.9.21 
[25] httpuv_1.3.3

**Comment by timelyportfolio** [comment]
@njburgoyne, do you have some minimal sample code?  I'd like to work through this, but I don't have an understanding of `shinyFiles`.

**Comment by njburgoyne** [comment]
...was just editing

**Comment by timelyportfolio** [comment]
For reference, the old `htmlwidgets` template uses `renderValue`, so we could possibly fix by using the new template.

**Comment by njburgoyne** [comment]
Sorry, I think you are right. I may have confused the issue - `shinyFiles` doesn't use `htmlWidgets`. However, there **_is_** crosstalk between the two packages but not where I mentioned it (not a js expert). My bad. Sorry for the redherring.

**Comment by smartinsightsfromdata** [comment]
@thomasp85 @njburgoyne

I tried to see if I could see anything untoward. Unfortunately with RStudio Server on OSX (configured with homebrew) & shiny 0.14 I couldn't make the shinyfiles own demo work:

The file button gave error
The folder button showed a directory, but I couldn't click on anything (i.e. I tried with no effects).
Without a proper working demo of shinyfiles I'm stuck.
