### ISSUE TITLE
Adding multiple metrics 

### ISSUE THREAD

**Issue by ElianoMarques** [smartinsightsfromdata/rpivotTable#54]
Hi, is there a way to add multiple summarised attributes? e.g. two mean attributes?

**Comment by smartinsightsfromdata** [comment]
Hi.  I am not entirely sure of the advantage of doing this within rpivotTable.
R allows to add any type of attribute very easily. 
This "ease of use" is not exactly there in javascript, hence the effort of @nicolaskruchten to add derived attributes.  I do not dismiss derived attributes, but I do not see presently their value from an R ecosystem point of view. Awaiting to be convinced :)
