### ISSUE TITLE
How to remove the drag and drop UI interface?

### ISSUE THREAD

**Issue by ebergel** [smartinsightsfromdata/rpivotTable#56]
rpivottable is exposing the tables with a drag'n'drop UI around it, using pivotUI(). Is there any way to remove the UI interface, essentially using pivottable.js  pivot() ?

**Comment by ebergel** [comment]
found the solution in /inst/htmlwidgets/rpivotTable.js

$('#'+el.id).pivotUI(
      		x.data, x.params, true, x.locale
      ); 

to
$('#'+el.id).pivot(
      		x.data, x.params, true, x.locale
      );

**Comment by smartinsightsfromdata** [comment]
Well done @ebergel , thanks!
