### ISSUE TITLE
Using rpivotTables in flexdashboard. 

### ISSUE THREAD

**Issue by ThoDuyNguyen** [smartinsightsfromdata/rpivotTable#58]
When using rpivotTable inside a flexdashboard with a long table, the dashboard could not display correctly. Only fixed viewpoint could be displayed. It would be nice if something like scrollbars appear. 

In shiny application, rpivotTable works fine

My declaration for flexdashboard

```
---
title: "Test rpivotTable"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    horizontal_layout: scroll
---
```

**Comment by voxnonecho** [comment]
You can fix this by adding:

    ---
    title: "Test rpivotTable"
    output: 
      flexdashboard::flex_dashboard:
        css: style.css
        orientation: columns
---

And in `style.css`:

    .rpivotTable{ overflow-x: scroll; }

**Comment by ThoDuyNguyen** [comment]
I'll retest and feedback soon. 

Thank you for the help

**Comment by ThoDuyNguyen** [comment]
@voxnonecho: Your solution fixed my problem. 💯 

Case closed.

**Comment by aditya-kothari** [comment]
@voxnonecho You are awesome man!
