### ISSUE TITLE
Interface styling options

### ISSUE THREAD

**Issue by aruberutou** [smartinsightsfromdata/rpivotTable#59]
Hello, gents,

Excellent work here. I'm working with Shiny. This package has been a godsend, literally. Thank you.

One rough are, however, is related to aesthetics. Any chance for better control over table aesthetics, directly from within R? For example, maximum column sizes or a separable, absolute table for the filters? Also, options to move the legends around would be nice.

I am happy to work on this myself, but have only rudimentary java and css skills. I am, however, willing to put in the effort to learn. Ideally, this could rival--say--Tableau in terms of overall UX.

Anyone willing to help me get started int his direction?

**Comment by shapenaji** [comment]
On this note, I've been digging into the underlying package, and this appears to be the base CSS, those !important tags are going to make it somewhat rough to restyle here right?:

```
.table {font-family: Helvetica;}
.node  {
    border: solid 1px white;
    font: 9px tahoma;
    line-height: 10px;
    overflow: hidden;
    text-indent: 2px;
    position : absolute;

    }
 .c3-line, .c3-focused {stroke-width: 3px !important;}
 .c3-bar {stroke: white !important; stroke-width: 1;}
 .c3 text { font-size: 12px; color: grey;}
 .tick line {stroke: white;}
 .c3-axis path {stroke: grey;}
 .c3-circle { opacity: 1 ! important;}
 .pvtRows, .pvtCols {background: #54B4EB none repeat scroll 0 0;}
 .pvtFilteredAttribute { font-weight: bold;}
```

**Comment by smartinsightsfromdata** [comment]
Actually that is not correct (if only!). The `css` code reported above is only for the `C3` renderer used for the `C3` treemap and it is in `rpivotTable.css`. 

The actual `css` code is more complex and is  in `pivot.min.css`.

Part of the problem @aruberutou is encountering is that the basic renderers of rpivotTable (pivottable.js) are dynamic.  Suppose you are slicing data by a time dimension with months. Then you add days. Suddenly you go from 12 to 365 elements either on rows or columns. 
This is why this widget cannot be easily fixed (it would mean add the ability to scroll within a pre-defined window, at the moment absent in the current renderers).

There is an additional renderer recently added to the family: [NovixPivotJS](https://github.com/fbrussa/NovixPivotJS). 

The demo on the github page shows h. / v. scroll bars.  It should be easy to add this renderer.

Probably adding a parameter as I don't think it co-exists with the other renderers: for example, today the `C3` renderer (the treemap) and the `D3` renderer (e.g. the scatterplot) coexist in the the same pull down menu on the pivottable.

`NovixPivotJS` is based on `handsontable.js` library and allows also write back, but for R it may be a complex feature to add, as the rhandsontable project is showing.

I will give a closer look at `NovixPivotJS`, but I welcome PR is anybody is willing.

**Comment by aruberutou** [comment]
Wow. Thanks for the comments. Hadn't realised it was all so complex.

Happy to put in the leg work, to make it happen. Any tips?

**Comment by smartinsightsfromdata** [comment]
Sadly `NovixPivotJS`, which I was thinking at as a possible solution, is based on `highchart`, which I thought was open source but it is a paying for graphic library.
