### ISSUE TITLE
New project proposal

### ISSUE THREAD

**Issue by smartinsightsfromdata** [smartinsightsfromdata/rpivotTable#60]
This is a proposal for all interested parties, but especially @jrowen,  @timelyportfolio & @nicolaskruchten  to see if this proposal may wet their appetite.

We have a decent `pivottable` widget with `rpivotTable`, based on `pivottable.js`

I recently discovered that there is a custom project based on `pivottable.js`, that introduces `handsontable` as the base table,  and `highchart`.

The  [NovixPivotJS project](https://github.com/fbrussa/NovixPivotJS) is currently possibly abandoned, but it represents undoubtedly an advance.

The main advantages of `NovixPivotJS` vs. `pivottable` are:
- the table has vertical and horizontal scrollers.  This overcome one perceived limitation of `pivottable`: it is too dynamic.  The presence of scroll bars would make it an ideal widget for jupyter (in R and Python) and shiny.
- `handsontable` is a step improvement over existing table
- it is possible to enter data into the `pivottable` (i.e. in `handsontable`)

On the other hand the complexity of handling data entry, well familiar to @jrowen (and to me with my early experiments on `handsontable), and the introduction of `highchart` represent a level of complexity well beyond my meagre javascript skills.
There would be also the additional core of maintaining alignment with `pivottable`.

A team effort would seems a good way forward, sort of bringing together some elements of rhandsontable and rpivottable (both packages would continue to make sense as specialised versions).

In an ideal world this would require:

- @nicolaskruchten to integrate `NovixPivotJS` and maintain it in parallel to `pivottable` evolutions
- @jrowen to lend his expertise (and code) to make the data entry function work in R and in shiny
- @timelyportfolio to lend an hand
- @smartinsightsfromdata (me) to make as less of a mess as possible of any code
- any interested party to help

Does it sound feasible and worth the effort?

**Comment by smartinsightsfromdata** [comment]
Apologies for wasting everybody's time: I've just discovered that `highchart` is not open source, but actually quite expensive!

**Comment by nicolaskruchten** [comment]
In fact, `handsontable` is also not open source nor cheap :)

**Comment by jrowen** [comment]
Handsontable does have a free version,
https://docs.handsontable.com/0.28.1/tutorial-introduction.html, which is
what rhandsontable is built on.  The pro offering is something they
launched more recently.

**Comment by nicolaskruchten** [comment]
Indeed you're right. Their website doesn't put much emphasis on that, for
obvious reasons ...

**Comment by smartinsightsfromdata** [comment]
@nicolaskruchten would it be very complex to introduce scroll bars in pivottable (with present table or free version of handsontable)?

I'm thinking jupyter / rmarkdown / shinydashboard type of applications...

**Comment by nicolaskruchten** [comment]
You could probably do it in a couple of lines of jquery to add a css rule
like overflow: scroll...

**Comment by nicolaskruchten** [comment]
Here you go, just throw this into an `onRefresh` callback:

```javascript
$( ".pvtTable" ).wrap( "<div style='width: 400px; height: 400px; overflow: scroll;'></div>");
```
