### ISSUE TITLE
Confirm: "The rpivotTable package depends on the development version of the htmlwidgets package"?

### ISSUE THREAD

**Issue by GaryWMN** [smartinsightsfromdata/rpivotTable#61]
Does rpivotTable indeed still depend on the development version of the htmlwidgets package?

We are looking at upgrading our htmlwidgets package from 0.7 to 0.8.

**Comment by smartinsightsfromdata** [comment]
Gary, actually this is not true anymore (it was true when I first developed the package).  
I will amend the README.  

Thanks for pointing this out: the README is one of those things that you are not re-reading with new eyes from beginning to end every time you submit a new version, but just amend where necessary, with the result that something may slips through.

**Comment by GaryWMN** [comment]
Excellent! We will proceed with our upgrades. Thanks for replying so timely!
