### ISSUE TITLE
Export the data from rpivotTable in excel

### ISSUE THREAD

**Issue by EnricowithR** [smartinsightsfromdata/rpivotTable#62]
How can I export the data from rpivotTable in excel?

**Comment by smartinsightsfromdata** [comment]
The code below saves a csv.  It works but I didn't tested extensively: any feedback is appreciated.

Please note that the code itself is not particularly optimised.

```
library(shiny)
library(rpivotTable)
library(rvest)

x <- read.csv("./forest/srs3a.csv", stringsAsFactors = FALSE)

ui <- fluidPage(sidebarLayout( sidebarPanel(
  selectizeInput('row','Row:', choices = c('County','Unit','NULL')),
  actionButton("go","Go"),
  actionButton("save","Save"),
  selectizeInput('state','State:',choices = c('Alabama','Arkansas','Florida','Texas')),
  actionButton("map","Map")),

  mainPanel(tabsetPanel(type="tabs",
                      tabPanel("Table",rpivotTableOutput("table")),
                      tabPanel("Map")  ))
))

server <- function(input, output, session)
{

  session$onSessionEnded(stopApp)
  
  myrows <- eventReactive(input$go,
                          {switch(input$row,
                                  "County" = c("COUNTYCD"),
                                  "Unit" = c("UNITCD"))
                         })
  
  
  output$table <- renderRpivotTable({

    rpivotTable(x,
                rows=myrows(),col="CSC",
                aggregatorName="Sum",
                vals="acres",
                rendererName="Table",
                inclusions=list(STNAME=list(input$state)),
                onRefresh = htmlwidgets::JS("function(config) {Shiny.onInputChange('myData', 
                                            document.getElementById('table').innerHTML); 
  }"))
  })
  
  summarydf <- eventReactive(input$myData,{
    input$myData %>%
      read_html %>%
      html_table(fill = TRUE) %>%
      .[[2]]
  })
  
  observeEvent( input$save, {
    if(nrow(summarydf() )<1) return()
    write.csv(summarydf(), file="./forest.csv")
  })
  
}

shinyApp(ui = ui, server = server)
```

**Comment by EnricowithR** [comment]
Thanks. Is it possible to do that without shiny?

Am Samstag, 10. Dezember 2016 schrieb Enzo :

**Comment by smartinsightsfromdata** [comment]
The easy answer is no, you need `shiny`: its scaffolding offers the mean to access the web page and get the data displayed.

For example, while you can use `rpivotTable` in `jupyter` with the `R kernel`, `jupyter` does not offer at the moment the mechanism to get the data from `rpivotTable` as we do in `shiny` (of course it could be added in the future).

As an alternative, it would be interesting to try with `shiny gadgets` and `rstudio addins`.

**Comment by smartinsightsfromdata** [comment]
@EnricowithR   see example from @Avatoo to see if ti works for you

https://github.com/smartinsightsfromdata/rpivotTable/issues/68

**Comment by roshi4datascience** [comment]
hi I want to create shiny aap which help me create pivot table and download results can you help me with example thanks in advance

**Comment by ascotchmer** [comment]
The above code is very useful but only when the pivot is rendered as a table.  Is it possible to export a csv when a barchart is selected?  In other words, no matter how the data is rendered in rpivottable, the export will always be as though Table was the renderer.

**Comment by omargiorgetti** [comment]
[rpivotTabletocsv](https://github.com/omargiorgetti/rpivotTabletocsv)

**Comment by stvrd** [comment]
Hi,

There is an excellent solution for JS pivottable: 
https://github.com/nicolaskruchten/pivottable/wiki/Optional-Extra-Renderers#exporting-to-tsv-demo
how can we use the optional extra renderer 'Export to tsv' in rpivottable?

**Comment by ChristopherMarais** [comment]
Is there solution for this yet similar to the JS pivottable?
