### ISSUE TITLE
New version of PivotTable.js!

### ISSUE THREAD

**Issue by nicolaskruchten** [smartinsightsfromdata/rpivotTable#64]
Just FYI there are some nice improvements in the latest version of PivotTable.js, especially around the filter menu... The API should be unchanged: https://github.com/nicolaskruchten/pivottable/releases

**Comment by frajuegies** [comment]
Dear Nicolas
... would you please indicate which subdirectories I have to replace in the "old" rpivottable library?
Sorry, for the "newbee" question....

Thank you very much in advance
Jürgen

**Comment by nicolaskruchten** [comment]
Hi Jürgen,

This is something that would need to be done in this repository, rather than on your local machine if you're just using this library... To answer your question, as far as I can tell, it seems like https://github.com/smartinsightsfromdata/rpivotTable/blob/master/inst/htmlwidgets/rpivotTable.yaml needs to be updated and some command needs to be run to update the dependencies, but I'm not super-familiar with the `htmlwidgets` system being used here...

Nicolas

**Comment by smartinsightsfromdata** [comment]
@frajuegies I will update rpivotTable this weekend - also for a doc issue recently picked up by CRAN :)

**Comment by frajuegies** [comment]
Nicolas, thank you very much.....that's great

Best regards,
Jürgen

**Comment by frajuegies** [comment]
@smartinsightsfromdata Thank you for picking this up ! Best regards, Jürgen

**Comment by frajuegies** [comment]
As I was too curieux to work with numeric filters and regex expressions.... 
... so I just replaced a directory

Here are my steps....
1. Find the rpivotable directory and change into that subdirectory
you find the (system) libraries by typing .Library in a R command line

2. Rename the dist subdirectory (.... htmlwidgets/lib/pivottable/dist) to "safe" it.

3. Download the repository pivottable as zip-file from https://github.com/nicolaskruchten/pivottable

4. Extract the files

5. Copy the dist subdirectory in the rpivottable/htmlwidgets/lib/pivottable/dist directory to replace the old version.

I do know that this method is **not** sustainable... as you might/will loose this manual update if the package is updated.
This "update" works fine on my setups under R 3.3.1 (Win7, Mac OS and Ubuntu Server 14.04 running Shiny Server)

Best regards,
Jürgen

**Comment by frkbr** [comment]
The latest release 2.11.0 of PivotTable.js seems to have added UI elements to control row/col ordering. That would be great to have in R too. Any chance of an updated R integration?

**Comment by smartinsightsfromdata** [comment]
Is coming.  I've just started to work on it. Thanks for your patience.

**Comment by smartinsightsfromdata** [comment]
To everyone.  Sorry it took so long to merge the new pivottable!

Now on github the rpivotTable version 2.0 is aligned to pivottable 2.11.0.

@nicolaskruchten I'm really impressed by the new release! Well done.
