### ISSUE TITLE
change_locale() doesn't work for "nl"

### ISSUE THREAD

**Issue by rdatasculptor** [smartinsightsfromdata/rpivotTable#66]
I was very happy to notice there was "nl" language support in this brilliant package. However, this setting seems to be the only one that doesn't work. When I do something like this:

`change_locale(rpivotTable(mtcars),"nl") `

nothing happens, no pivottable is being built. 

The other mentioned valid languages "es", "fr","pt" and "tr" cause no problems. 
Does the "nl"-problem have something to do with the issue mentioned [here](https://github.com/nicolaskruchten/pivottable/pull/532)?

Does anyone know how to solve this issue? Is there a quick fix?

**Comment by rdatasculptor** [comment]
I found the error. 

in the file "pivot.nl.min.js" there is a string that says: "e.pivotUtilities.locales.fr". I think this should be: "e.pivotUtilities.locales.nl" instead.

**Comment by smartinsightsfromdata** [comment]
@rdatasculptor The wrong file issue seems to be corrected in the latest version of pipottable just merged.
Please check if the nl locale now works ad report.  Many thanks!

**Comment by rdatasculptor** [comment]
Thank!
