### ISSUE TITLE
Export output with merged column or row names

### ISSUE THREAD

**Issue by Avatoo** [smartinsightsfromdata/rpivotTable#68]
Hi, I'm creating a shiny app around rpivotTable. A key requirement is to write the summary table to Excel spreadsheets etc. which has been done by copying this helpful post on issue #62. Ideally, the Excel output would look exactly like that of rpivotTable. However, when it's a 3-way, 4-way or 5-way table, the col/row names tend to be just duplicates instead of merged cells. I'm trying to re-format the headers in R just before the table gets exported, but also wondering if tweaking the JS code passed to the onRefresh argument can do the job quicker. Any clue?

Attached below are two example tables. Thanks!

![image](https://cloud.githubusercontent.com/assets/6826099/23369713/2f306ff0-fd0a-11e6-9a05-728d1e70de79.png)

![image](https://cloud.githubusercontent.com/assets/6826099/23369727/3ac2dc0e-fd0a-11e6-81a3-365a337013e0.png)

**Comment by smartinsightsfromdata** [comment]
As I commented in #62  I think this functionality needs further testing, so many thanks for picking this up.

As far as specific lines of investigation to solve the problem, as you has seen, the parsing of the html data from the `Shiny.onInputChange` function is done using `rvest::html_table`. 

I wonder if, using other web scraping packages  / functions for the conversion, this would give the same output?

I confess I do not use web scraping tools in R much, so any help would be appreciated.

**Comment by Avatoo** [comment]
Unfortunately, I'm not an html ninja either. After a bit of search, I'm using package [`htmltab`](https://cran.r-project.org/web/packages/htmltab/vignettes/htmltab.html) because it perfectly identifies header information. For example, multiple levels are separate by " >> ".  Excel cells are then merged by `openxlsx::mergeCells()` when needed. Please let me know if you have better solutions than my hacky way. The below function can be used in a `downloadHandler()`. 

```
writePvt2Xlsx <- function(cols = c("Class","Sex", "Age"),
                          rows = "Survived",
                          URL = "titanic.html",
                          outFile) {
  if (missing(outFile)) {
    outFile <- gsub('.html', "", basename(URL), ignore.case=TRUE)
    outFile <- paste0(outFile, ".xlsx")    
  }
  
  res <- htmltab(doc = URL, headerSep = " >> ",
                 which = 2, rm_nodata_cols = FALSE)
  
  ## Remove Totals duplicate in last row
  #res[nrow(res), 1:(length(rows)-1)] <- NA

  df <- data.frame(x = names(res))
  if (!is.null(cols)) {
    df <- df %>% separate(x, cols, sep = " >> ", fill = "left")
  } 

  ## Create a new workbook
  wb <- createWorkbook()
  
  ## Add a worksheet
  addWorksheet(wb, "Sheet 1")
  
  ## Write data
  writeData(wb, "Sheet 1", t(df), colNames = FALSE, rowNames = FALSE)
  writeData(wb, "Sheet 1", res, startRow = ncol(df) + 1, colNames = FALSE, rowNames = FALSE)

  #-------------------
  # Remove dulicate rows
  if(!is.null(rows) & !is.null(cols)) {
    for (i in ncol(df) + 1:nrow(res)) mergeCells(wb, "Sheet 1", cols = length(rows):(length(rows) + 1), rows = i)
  }
  
  #--------------------
  # Merge dulicate row names 
  if (length(rows) > 1) {
    for (rowth in 1:(length(rows) - 1)) {
      rowvar <- rows[rowth] 
      res2 <- unite_(res, rowvar, rows[1:rowth], sep = " >> ")
      tar <- res2[, rowvar]
      
      for (levelth in levels(as.factor(tar))) {
        mergeCells(wb, "Sheet 1", cols = rowth, rows = ncol(df) + which(tar %in% levelth))
      }
    }
  }

  #-------------------
  # Merge duplicate column names
  if (length(cols) > 1) {
    for (colth in 1:(length(cols) - 1)) {
      colvar <- cols[colth]
      df2 <- unite_(df, colvar, cols[1:colth], sep = " >> ")
      tar <- df2[, colvar]
      
      varlevel <- levels(as.factor(tar))[!str_detect(levels(as.factor(tar)), "NA")]
      for (levelth in varlevel) {
        #tar <- df[, colth]
        mergeCells(wb, "Sheet 1", cols = which(tar %in% levelth), rows = colth)
      }
    }
  }
  

  ## Save workbook
  saveWorkbook(wb, outFile, overwrite = TRUE)
}
```

**Comment by smartinsightsfromdata** [comment]
@Avatoo many thanks for your contribution!

**Comment by SaadAmin5** [comment]
Hi @Avatoo , could you please post all the codes of Titanic data? It would be really helpful as I'm facing the same issue. Thanks
