### ISSUE TITLE
`change_locale` not working.

### ISSUE THREAD

**Issue by nicholaelaw** [smartinsightsfromdata/rpivotTable#73]
Just had a quick trial of the package. Somehow none of the extra locales are working for me. Anything other than English gives an empty page. And if loaded in Chrome, the following errors are logged in the console:

    Uncaught TypeError: Cannot read property 'renderers' of undefined
        at Object.renderValue (rpivotTable.js:24)
        at htmlwidgets.js:625
        at Array.forEach (<anonymous>)
        at forEach (htmlwidgets.js:55)
        at htmlwidgets.js:551
        at Array.forEach (<anonymous>)
        at forEach (htmlwidgets.js:55)
        at Object.window.HTMLWidgets.staticRender (htmlwidgets.js:549)
        at HTMLDocument.<anonymous> (htmlwidgets.js:638)

I used the example given in the tutorial: 

```r
data(mtcars)
change_locale(rpivotTable(mtcars), 'zh')
```

So I dug into the temp files, and found the problem: for reasons unknown, the output folder `lib/pivottable-zh-1.6.3` is missing its content. I copied over `pivot.zh.min.js` from the package, and the page is loading fine now.

As I have encountered this sort of behaviour with other packages (flexdashboard, plotly), I am absolutely clueless as how to fix this.

Also, I found a piece of code that looks suspicious at line 33 of  `locale.R`:

    system.file("htmlwidgets/lib/pivottable/dist",package="rpivotTable")

It seems that this file, whatever it was meant to do, does not exist in the package. Not sure it's related. Just something that doesn't seem right.

**Comment by nicolaskruchten** [comment]
This should be fixed in version 0.3.0 of this library! https://github.com/smartinsightsfromdata/rpivotTable/releases/tag/v0.3.0

**Comment by nicholaelaw** [comment]
Nicely done!
