### ISSUE TITLE
add subtotal plugin

### ISSUE THREAD

**Issue by timelyportfolio** [smartinsightsfromdata/rpivotTable#74]
I will volunteer to do this, but wanted to file an issue to track progress.  Add [subtotal plugin](https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer).  @smartinsightsfromdata, any objections?

**Comment by nicolaskruchten** [comment]
This should be fixed in version 0.3.0 of this library! https://github.com/smartinsightsfromdata/rpivotTable/releases/tag/v0.3.0
