### ISSUE TITLE
Updating PivotTable.js

### ISSUE THREAD

**Issue by nicolaskruchten** [smartinsightsfromdata/rpivotTable#76]
I've just released a bugfix version of the library and would like to help you integrate it... If you let me know what the steps are to upgrade it, I can provide you with PRs whenever I release a new version, to help keep things in sync more smoothly :)

**Comment by smartinsightsfromdata** [comment]
Hi Nicolas


It is certainly something worth considering.

Please let me know how I could facilitate this.

Thanks

Enzo

**Comment by nicolaskruchten** [comment]
Cool! Ideally just a readme with steps to upgrade... do you just replace
some files or is there a set of commands to run or...?
