### ISSUE TITLE
Table renders aggregate zeros as blank instead of "0" 

### ISSUE THREAD

**Issue by kalinagrawal** [smartinsightsfromdata/rpivotTable#83]
When an aggregate value is 0 (zero), the pivot table cell shows a blank instead of "0". I think this should show a true "0" to distinguish between:

- data is present and aggregates to zero
- row/column labels present, but missing data.

Here's an RPubs.com pub that shows the issue and how to reproduce it.

Thanks for your hard work!!

http://rpubs.com/kagrawal/332425

PS: I reported this bug on the [PivotTable GitHub issues](https://github.com/nicolaskruchten/pivottable/issues/832) and nicolaskruchten  kindly mentioned that the issue is resolved in PivotTable.js version 2.14.0 but rpivotTable still uses version 2.11.0 .

I'm not sure how to update rpivotTable's use of PivotTable.js, however...

Thank you!

**Comment by nicolaskruchten** [comment]
This should be fixed in version 0.3.0 of this library! https://github.com/smartinsightsfromdata/rpivotTable/releases/tag/v0.3.0
