### ISSUE TITLE
Order in "List unique values"

### ISSUE THREAD

**Issue by rubemd** [smartinsightsfromdata/rpivotTable#85]
Hi! First of all, congratulations for this excellent tool. It is really handy!

I am just in some trouble when selecting "List unique values" as I can't understand how it sorts neither I could do something to change its sorting. I tried, without success, changing the target field from numbers or letters. Maybe you can better understand with the following figures.

<img width="786" alt="captura de tela 2018-01-03 23 32 20" src="https://user-images.githubusercontent.com/25906665/34547062-7d4491de-f0df-11e7-90cc-e42ad5ca4c44.png">
<img width="667" alt="captura de tela 2018-01-03 23 32 00" src="https://user-images.githubusercontent.com/25906665/34547063-7d6583c6-f0df-11e7-92ce-177a11de5841.png">

In both figures, you can see that the order is probably the order of the data, as in "Campanha 3". The area number 5 or EA05 appears below all other values. This happens with other "Campanha" too.

What am I doing wrong? Do you have some advice to give me in this respect?

Thank you very much indeed!

Rubem.

**Comment by nicolaskruchten** [comment]
This is something which will need to be fixed in the underlying Javascript library. I've created a corresponding issue in that repository: https://github.com/nicolaskruchten/pivottable/issues/854

**Comment by nicolaskruchten** [comment]
This should be fixed in version 0.3.0 of this library! https://github.com/smartinsightsfromdata/rpivotTable/releases/tag/v0.3.0
