### ISSUE TITLE
Assigning different aggregators to different columns in rpivotTable. 

### ISSUE THREAD

**Issue by mohsenlaleh** [smartinsightsfromdata/rpivotTable#93]
I just want to know that is there any way to assign different aggregators to different columns in rpivotTable or not?
Some of my columns are just values and I can use "Sum" aggregator (in this example "Sales" and "ITPSales") but for others (I want to calculate "ITP" column), I need to use "Sum over Sum". I know I could calculate the needed column in r first and then use the rpivotTable but in this way, subtotal does not show the correct values for the calculated field. using subtotal is necessary for me.

library(reshape2)
library(rpivotTable)
df <- data.frame("Company" = c("A","A","A","B","B","B"), 
                 "Brand" = c("Ax","Ay","Az","Bx","By","Bz"),
                 "Sales" = c(10,15,20,8,10,12),
                 "ITPSales" = c(150,60,40,32,5,24))
#It is OK but I need other columns too.
rpivotTable(df,
            rows = c("Company", "Brand"),
            aggregatorName = "Sum over Sum",
            vals = c("ITPSales", "Sales"),
            subtotals = TRUE
            )
I need both columns ("Sales", "ITP) simultaneously (value column and calculated one) for this purpose, I'll do as follows:
df$ITP <- df$ITPSales / df$Sales
df_melt <- melt(df,1:2)
rpivotTable(df_melt,
            rows = c("Company", "Brand"),
            cols = "variable",
            aggregatorName = "Sum",
            exclusions= list( variable = list( "ITPSales")),
            vals = "value",
            subtotals = T
            )
As you can see subtotal for ITP column is not correct.
I think if there were an option for assigning different aggregators to different columns, it could solve the problem. 
thanks.

**Comment by nicolaskruchten** [comment]
It’s not possible to use different aggregators for different parts of the
table, no.

**Comment by mohsenlaleh** [comment]
Thank you very much for your attention.
